'use strict'

export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'

export const GAME_STATE_CHANGED = 'GAME_STATE_CHANGED'
export const CHAT_LOADED = 'CHAT_LOADED'
export const ROOM_LOADED = 'ROOM_LOADED'
export const ROOMS_LOADED = 'ROOMS_LOADED'
export const SUSPECTS_LOADED = 'SUSPECTS_LOADED'
export const EVIDENCES_LOADED = 'EVIDENCES_LOADED'
export const EVIDENCES1_LOADED = 'EVIDENCES1_LOADED'
export const EVIDENCE_ADDED = 'EVIDENCE_ADDED'
